-- Copied from ~/lean/apnlift/APNLift/Core/ReducedRepresentative.lean (apnlift, H. Fukui; sha256 175726f4e34d28a7…)
-- on 2026-10-07; only the namespace APNLift -> ResidueAPN and the import path were changed.
import Mathlib

/-!
# The reduced representative

Specification entry S1.

Every function on a finite field is the evaluation of exactly one polynomial of degree less than
the field order.  That polynomial is the *reduced representative*, ∧ it is the object whose
formal derivative the whole project uses.

The degree bound is not decoration.  `X ^ q - X` is the zero function on a field of order `q`,
so functions do not determine polynomials; they determine polynomials *of degree below q*.  A
formal derivative therefore cannot be defined on functions, nor on the quotient by the ideal
generated by `X ^ q - X`: it is defined on the representative.
-/

namespace ResidueAPN

open Polynomial

variable {F : Type*} [Field F] [Fintype F] [DecidableEq F]

/-- The unique polynomial of degree `< |F|` whose evaluation is `f`. -/
noncomputable def rep (f : F -> F) : F[X] :=
  Lagrange.interpolate Finset.univ id f

@[simp] theorem eval_rep (f : F -> F) (x : F) : (rep f).eval x = f x := by
  simpa [rep] using
    Lagrange.eval_interpolate_at_node (s := Finset.univ) (v := (id : F -> F)) f
      Function.injective_id.injOn (Finset.mem_univ x)

theorem degree_rep_lt (f : F -> F) : (rep f).degree < Fintype.card F := by
  simpa [rep, Finset.card_univ] using
    Lagrange.degree_interpolate_lt (s := Finset.univ) (v := (id : F -> F)) f
      Function.injective_id.injOn

/-- Uniqueness: anything of degree `< |F|` with the same values *is* the representative. -/
theorem rep_unique {f : F -> F} {p : F[X]} (hdeg : p.degree < Fintype.card F)
    (heval : ∀ x : F, p.eval x = f x) : p = rep f := by
  refine Lagrange.eq_interpolate_of_eval_eq (s := Finset.univ) (v := (id : F -> F)) f
    Function.injective_id.injOn ?_ ?_
  . simpa [Finset.card_univ] using hdeg
  . intro i _
    simpa using heval i

/-- Two polynomials below the degree bound with the same values are equal. -/
theorem eq_of_degree_lt_of_eval_eq {p q : F[X]} (hp : p.degree < Fintype.card F)
    (hq : q.degree < Fintype.card F) (h : ∀ x : F, p.eval x = q.eval x) : p = q :=
  eq_of_degrees_lt_of_eval_finset_eq Finset.univ hp hq (fun x _ => h x)

theorem rep_zero : rep (fun _ : F => (0 : F)) = 0 := by
  symm
  refine rep_unique ?_ ?_
  . simp
  . intro x; simp

section DegreeBoundIsNecessary

/-!
## Negative control for specification rule 4

The specification forbids defining the formal derivative on functions, or on the quotient by
`X ^ q - X`.  The three results below are the reason, proved rather than asserted: `X ^ q - X`
is the zero function, it is not the zero polynomial, and its formal derivative is `-1`.  So the
derivative does not descend along "same function", and a representative must be chosen.
-/

variable (F)

theorem eval_X_pow_card_sub_X (x : F) :
    (X ^ (Fintype.card F) - X : F[X]).eval x = 0 := by
  simp [FiniteField.pow_card]

theorem derivative_X_pow_card_sub_X :
    derivative (X ^ (Fintype.card F) - X : F[X]) = -1 := by
  rw [derivative_sub, derivative_X_pow, derivative_X, FiniteField.cast_card_eq_zero]
  simp

theorem X_pow_card_sub_X_ne_zero : (X ^ (Fintype.card F) - X : F[X]) ≠ 0 := by
  intro h
  have hd := derivative_X_pow_card_sub_X F
  rw [h, derivative_zero] at hd
  exact (neg_ne_zero.mpr (one_ne_zero)) hd.symm

/-- Two different polynomials with the same evaluation.  Without the degree bound there is no
unique representative and no well-defined derivative. -/
theorem exists_ne_with_same_eval :
    ∃ p q : F[X], p ≠ q ∧ ∀ x : F, p.eval x = q.eval x :=
  ⟨X ^ (Fintype.card F) - X, 0, by simpa using X_pow_card_sub_X_ne_zero F,
    by intro x; simpa using eval_X_pow_card_sub_X F x⟩

end DegreeBoundIsNecessary

end ResidueAPN
