import ResidueAPN

/-!
AuditAxiomsAll (generated by papers/tools/gen_lean_release_meta.py from formalization/leanmap.json).
Prints the axioms of every declaration that the paper <-> Lean map names. `run_release.sh` accepts the run
only if each of them has its own axiom line, no line contains sorryAx, and every listed axiom is one of
propext, Classical.choice, Quot.sound. This file states no theorem; it does not check that a type means what
the paper says (that is AuditStage1/2 for the restated types and MEANING_MAP.md for the definitions).
-/

#print axioms ResidueAPN.card_fibre
#print axioms ResidueAPN.card_kerL_of_dvd
#print axioms ResidueAPN.card_ker_mul
#print axioms ResidueAPN.card_roots_polG
#print axioms ResidueAPN.card_suppP
#print axioms ResidueAPN.derivative_eval_eq_zero_iff
#print axioms ResidueAPN.derivative_polP_eq_pow
#print axioms ResidueAPN.derivative_quadratic
#print axioms ResidueAPN.det_B_ne_zero
#print axioms ResidueAPN.eval_polP
#print axioms ResidueAPN.image_evalD
#print axioms ResidueAPN.isCoprime_polG_polE
#print axioms ResidueAPN.isOptimalAPNPerm_P
#print axioms ResidueAPN.lemma_2_2
#print axioms ResidueAPN.lemma_2_2_core
#print axioms ResidueAPN.lift_reduces
#print axioms ResidueAPN.multiplicity_at_root
#print axioms ResidueAPN.natDegree_polP
#print axioms ResidueAPN.polP_add_one_eq_pow
#print axioms ResidueAPN.polP_eq_sum_supp
#print axioms ResidueAPN.propW
#print axioms ResidueAPN.prop_6_1
#print axioms ResidueAPN.prop_6_1_family
#print axioms ResidueAPN.proposition_5_1
#print axioms ResidueAPN.root_fixed_two_s
#print axioms ResidueAPN.root_not_fixed_of_coprime
#print axioms ResidueAPN.root_not_fixed_s
#print axioms ResidueAPN.separable_polG
#print axioms ResidueAPN.theorem_3_1
#print axioms ResidueAPN.thm_6_2_top
#print axioms ResidueAPN.thm_6_2_top_family
#print axioms ResidueAPN.thm_6_2_unit
#print axioms ResidueAPN.thm_6_2_unit_family
