#!/usr/bin/env python3
"""gen_statement_map.py -- formalization/STATEMENT_MAP.md from formalization/leanmap.json (single source) and the
paper's numbering (the paper's manuscript.aux). Run from papers/:  python3 tools/gen_statement_map.py [--check] [--out F]
--check: exit 1 if STATEMENT_MAP.md differs from what would be generated."""
import json, re, sys
from pathlib import Path
sys.dont_write_bytecode = True
ROOT = Path(__file__).resolve().parents[1]
AUX = next((c for c in (ROOT / 'paper' / 'manuscript.aux', ROOT.parent / 'paper_R5' / 'manuscript.aux') if c.is_file()),  # dev-layout fallback
           ROOT / 'paper' / 'manuscript.aux')   # release layout first, then the development layout
KIND = {'lem': 'Lemma', 'thm': 'Theorem', 'cor': 'Corollary', 'prop': 'Proposition', 'rem': 'Remark', 'def': 'Definition'}

def number(aux, label):
    m = re.search(r'\\newlabel\{' + re.escape(label) + r'\}\{\{([^}]*)\}', aux)
    return (KIND.get(label.split(':')[0], '') + ' ' + m.group(1)).strip() if m else '?'

def gen():
    lm = json.loads((ROOT / 'formalization/leanmap.json').read_text(encoding='utf-8'))['nodes']
    aux = AUX.read_text(encoding='utf-8')
    L = ['# STATEMENT_MAP — paper_R5 ↔ Lean (ResidueAPN); generated by tools/gen_statement_map.py from leanmap.json and the paper\'s .aux; do not edit by hand', '',
         'Trust labels: F = Lean 4 kernel-checked statement (axioms a subset of propext, Classical.choice, Quot.sound; no sorry); '
         '"F (...) + M" = only the named part is formal; M = proved in the paper only; L = cited; Def / Rem. '
         'A name listed here exists as a theorem (blueprint gate G5, a name check, not a type check) and has an axiom line in '
         '`lean/residue_apn_portable/audit/AuditAxiomsAll.lean`; the types are restated in `audit/AuditStage1.lean`, '
         '`audit/AuditStage2.lean` (type compatibility) and read against the paper in `MEANING_MAP.md` (meaning). '
         'The Galois-ring step of §6 is `GR_BRIDGE.md`.', '',
         '| label | number | trust | Lean declarations | note |', '|---|---|---|---|---|']
    for lab, e in lm.items():
        L.append('| %s | %s | %s | %s | %s |' % (lab, number(aux, lab), e['trust'],
                 (', '.join('`%s`' % d for d in e['lean']) + ('; definitions: ' + ', '.join('`%s`' % d for d in e.get('lean_defs', [])) if e.get('lean_defs') else '')).lstrip('; ') or '—', e.get('note', '')))
    return '\n'.join(L) + '\n'

def main():
    t = gen(); out = ROOT / 'formalization/STATEMENT_MAP.md'
    if '--out' in sys.argv: out = Path(sys.argv[sys.argv.index('--out') + 1])
    if '--check' in sys.argv:
        good = out.is_file() and out.read_text(encoding='utf-8') == t
        print('STATEMENT_MAP_CHECK=' + ('PASS' if good else 'FAIL')); sys.exit(0 if good else 1)
    out.write_text(t, encoding='utf-8'); print('written', out)

if __name__ == '__main__':
    main()
