#!/usr/bin/env python3
"""gen_lean_release_meta.py -- from formalization/leanmap.json (single source) generate
  lean/FINAL_DECLARATIONS.txt                         every Lean name listed in leanmap.json (sorted, unique)
  lean/residue_apn_portable/audit/AuditAxiomsAll.lean  `#print axioms` for each of them
Run from papers/:  python3 tools/gen_lean_release_meta.py [--check]
--check: exit 1 if either file differs from what would be generated (used by the release verifier)."""
import json, sys
from pathlib import Path
sys.dont_write_bytecode = True
ROOT = Path(__file__).resolve().parents[1]

def gen():
    lm = json.loads((ROOT / 'formalization/leanmap.json').read_text(encoding='utf-8'))['nodes']
    names = sorted({d for e in lm.values() for d in e['lean']})
    fin = '# Generated by tools/gen_lean_release_meta.py from formalization/leanmap.json; do not edit by hand.\n' \
          '# run_release.sh requires an axiom line for each name below in the audit output.\n' + '\n'.join(names) + '\n'
    aud = ['import ResidueAPN', '',
           '/-!',
           'AuditAxiomsAll (generated by papers/tools/gen_lean_release_meta.py from formalization/leanmap.json).',
           'Prints the axioms of every declaration that the paper <-> Lean map names. `run_release.sh` accepts the run',
           'only if each of them has its own axiom line, no line contains sorryAx, and every listed axiom is one of',
           'propext, Classical.choice, Quot.sound. This file states no theorem; it does not check that a type means what',
           'the paper says (that is AuditStage1/2 for the restated types and MEANING_MAP.md for the definitions).',
           '-/', '']
    aud += ['#print axioms %s' % n for n in names]
    return {'lean/FINAL_DECLARATIONS.txt': fin,
            'lean/residue_apn_portable/audit/AuditAxiomsAll.lean': '\n'.join(aud) + '\n'}, len(names)

def main():
    files, n = gen()
    if '--check' in sys.argv:
        bad = [p for p, t in files.items() if not (ROOT / p).is_file() or (ROOT / p).read_text(encoding='utf-8') != t]
        print('LEAN_META_CHECK=' + ('PASS' if not bad else 'FAIL ' + ' '.join(bad)), n)
        sys.exit(1 if bad else 0)
    for p, t in files.items():
        (ROOT / p).parent.mkdir(parents=True, exist_ok=True)
        (ROOT / p).write_text(t, encoding='utf-8')
    print('written', list(files), 'names', n)

if __name__ == '__main__':
    main()
